version: '3.1'

services :

  db:
    image: postgres
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    networks:
      - "psql"
    volumes:
      - db:/postgres/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  psql:
    driver: bridge